/**
 * Replay persistence layer — AC 30101 Sub-AC 1.
 *
 * What this module is
 * ===================
 *
 * The browser-side persistent home for finished replays. Where
 * {@link ./RecordingController} owns the live capture and
 * {@link ./downloadReplay} pushes a single file to the user's "Downloads"
 * folder, this module owns the **library** — the set of replays the
 * player accumulates over many sessions, browseable from the (later-AC)
 * replay menu and surfaceable as VCR fodder.
 *
 * Three backends, one interface
 * -----------------------------
 *
 *   1. {@link IndexedDBReplayStorage} (primary) — large quota,
 *      structured-clone payloads, async API. Default on Chrome desktop
 *      where M5 needs to live.
 *   2. {@link LocalStorageReplayStorage} (fallback) — tiny ~5 MB quota,
 *      synchronous, but universally available even in private-mode
 *      Firefox where IndexedDB sometimes refuses to open. Auto-selected
 *      when IDB is unusable.
 *   3. {@link MemoryReplayStorage} — non-persistent, in-process. Used by
 *      vitest, by headless CLI tools, and as the "first run, never
 *      saves" sandbox.
 *
 * `ReplayStorage` is the shared interface every backend implements; the
 * {@link openReplayStorage} factory probes the runtime and returns the
 * best backend it can stand up. Callers code against the interface — the
 * replay menu doesn't know whether the row it just deleted lived in IDB
 * or in `localStorage`.
 *
 * CRUD shape
 * ----------
 *
 *   • {@link ReplayStorage.save | save}(replay, options?)        → metadata (id, savedAt, sizeBytes, …)
 *   • {@link ReplayStorage.load | load}(id)                      → StoredReplay | null
 *   • {@link ReplayStorage.list | list}()                        → metadata[]   (newest first)
 *   • {@link ReplayStorage.has  | has}(id)                       → boolean
 *   • {@link ReplayStorage.delete | delete}(id)                  → boolean      (true if a row was removed)
 *   • {@link ReplayStorage.clear | clear}()                      → void         (drops every replay)
 *   • {@link ReplayStorage.getStats | getStats}()                → { count, totalBytes, quotaBytes? }
 *
 * Every method returns a `Promise` even when the backend (localStorage,
 * memory) could answer synchronously. The async surface lets the replay
 * menu code one path that works against IndexedDB *and* the fallback —
 * branching on backend type would leak persistence details into the UI.
 *
 * Quota handling
 * --------------
 *
 * Browsers cap storage with a {@link DOMException} of name
 * `QuotaExceededError` (or, on older Firefox, `NS_ERROR_DOM_QUOTA_REACHED`).
 * Both IDB and localStorage backends catch the native failure, free the
 * partially-written row if any, and rethrow as
 * {@link ReplayStorageQuotaExceededError}. The replay menu can `catch (e)
 * { if (e instanceof ReplayStorageQuotaExceededError) showFreeUpToast() }`
 * without sniffing browser-vendor strings.
 *
 * Determinism
 * -----------
 *
 * The persistence layer is **outside** the gameplay determinism boundary.
 * Replays it stores are themselves deterministic (the
 * {@link ReplayFile} schema encodes seed + input timeline), but the *id*
 * a save returns and the `savedAt` timestamp it stamps come from
 * caller-injectable factories. The default factories use `crypto.randomUUID`
 * (or a counter fallback) and `Date.now()` so production gets unique
 * sortable rows; tests inject deterministic stubs to assert exact bytes.
 *
 * Phaser-free
 * -----------
 *
 * No Phaser, Matter, or HTMLCanvas imports. This module touches only
 * `globalThis.indexedDB`, `globalThis.localStorage`, `crypto.randomUUID`,
 * and `Date.now` — all of which are stubbable via constructor options
 * for unit testing under plain Node (vitest's default environment).
 */

import {
  REPLAY_FORMAT_MAGIC,
  REPLAY_FORMAT_VERSION,
  ReplayFileError,
  deserializeReplay,
  serializeReplay,
  serializeReplayToString,
  type ReplayFile,
  type SerializeReplayOptions,
} from './ReplayFile';
import {
  CHECKSUM_ALGORITHM,
  ReplayIntegrityError,
  computeReplayChecksum,
  verifyReplayChecksum,
  type ReplayChecksumAlgorithm,
} from './replayChecksum';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/**
 * Stable identifier for a stored replay. Generated by
 * {@link ReplayStorageOptions.idFactory} (default: `crypto.randomUUID`),
 * unique within a backend. The replay menu uses this as React/DOM
 * row keys; the (later-AC) share flow embeds it in URLs.
 */
export type ReplayStorageId = string;

/**
 * Lightweight summary returned by {@link ReplayStorage.list} so the
 * replay browser can render every row without loading every replay's
 * full input timeline.
 *
 * The fields are split across two sources:
 *
 *   • Backend-managed: `id`, `savedAt`, `sizeBytes` — derived at save
 *     time, not stored inside the {@link ReplayFile} itself.
 *   • Mirrored from the replay header so the UI can show stage / players
 *     / duration without hitting `load()` for every row.
 */
export interface StoredReplayMetadata {
  /** Unique id assigned at save time. */
  readonly id: ReplayStorageId;
  /** ISO 8601 timestamp the replay was *saved* (not recorded). */
  readonly savedAt: string;
  /** UTF-8 byte size of the serialised replay JSON. */
  readonly sizeBytes: number;
  /** Mirrored from `replay.metadata.recordedAt`. */
  readonly recordedAt: string;
  /** Mirrored from `replay.metadata.durationFrames`. */
  readonly durationFrames: number;
  /** Mirrored from `replay.metadata.notes` (truncated by serialiser to 1024). */
  readonly notes: string;
  /** Mirrored from `replay.matchConfig.stageId`. */
  readonly stageId: string;
  /** Mirrored from `replay.metadata.playerCount`. */
  readonly playerCount: number;
  /** Mirrored from `replay.rngSeed`. */
  readonly rngSeed: number;
  /** Engine `package.json#version` recorded at save time. */
  readonly engineVersion: string;
  /**
   * Integrity checksum of the serialised payload — AC 30104 Sub-AC 4.
   *
   * Computed once at save time from the canonical compact JSON
   * `serializeReplayForStorage` produces. The storage layer re-computes
   * the checksum on every load and throws
   * {@link ReplayIntegrityError} (re-wrapped as
   * {@link ReplayStorageError}) when the two disagree, so a corrupted
   * row never silently feeds bad bytes into the replay player.
   *
   * 16 lowercase hex characters (64 bits). Pinned to the algorithm
   * named by {@link checksumAlgorithm}; future algorithm bumps add a
   * new identifier rather than mutating this one in place.
   */
  readonly checksum: string;
  /**
   * Identifier of the algorithm used to produce {@link checksum}.
   * Carried alongside the checksum so a future migration can introduce
   * a stronger hash without invalidating old rows: the verifier
   * branches on this string to choose the matching implementation.
   *
   * Today: always `'fnv1a-64-v1'` — the only algorithm this build
   * understands. See {@link ./replayChecksum.CHECKSUM_ALGORITHM}.
   */
  readonly checksumAlgorithm: ReplayChecksumAlgorithm;
}

/**
 * Full stored replay record returned by {@link ReplayStorage.load}.
 * Wraps the {@link ReplayFile} with the storage-side metadata so the
 * caller doesn't have to make two trips for "load + show in list".
 */
export interface StoredReplay {
  /** Storage-side metadata (id, savedAt, sizeBytes, …). */
  readonly metadata: StoredReplayMetadata;
  /** The frozen, validated replay file payload. */
  readonly replay: ReplayFile;
}

/** Aggregate stats for {@link ReplayStorage.getStats}. */
export interface ReplayStorageStats {
  /** Number of replays currently stored. */
  readonly count: number;
  /** Sum of every replay's `sizeBytes`. */
  readonly totalBytes: number;
  /**
   * Browser-reported total quota in bytes when known
   * (`navigator.storage.estimate().quota`), otherwise `null`. Always
   * `null` for the localStorage backend — browsers don't expose
   * localStorage's per-origin cap programmatically.
   */
  readonly quotaBytes: number | null;
  /**
   * Browser-reported usage in bytes when known. For IDB this is the
   * `navigator.storage.estimate().usage` figure (which counts everything
   * the origin stores, not just replays). For localStorage and memory
   * this is the same as `totalBytes`.
   */
  readonly usageBytes: number | null;
  /** Backend kind that produced these stats — useful for HUD diagnostics. */
  readonly backend: ReplayStorageBackend;
}

/** Backend kind discriminator. */
export type ReplayStorageBackend = 'indexeddb' | 'localstorage' | 'memory';

/** Options for {@link ReplayStorage.save}. */
export interface SaveReplayOptions {
  /**
   * Pre-allocated id. Optional — when omitted the storage generates one
   * via the configured `idFactory`. The (later-AC) "rename replay" flow
   * uses this to overwrite an existing row in place.
   */
  readonly id?: ReplayStorageId;
  /**
   * Wall-clock instant to stamp into `metadata.savedAt`. Defaults to a
   * `now()` call on the configured time source. Passing an explicit
   * value keeps tests stable.
   */
  readonly savedAt?: Date;
  /**
   * If true and a row with the given id already exists, overwrite it.
   * Otherwise, throw {@link ReplayStorageError}. Defaults to `false`
   * to prevent accidentally clobbering a previous match.
   */
  readonly overwrite?: boolean;
}

/** Shared constructor options across every backend. */
export interface ReplayStorageOptions {
  /**
   * Factory invoked once per `save()` to produce a row id. Defaults to
   * `crypto.randomUUID()` when available, otherwise a monotonic counter
   * suffixed with the wall clock. Tests inject a deterministic stub so
   * assertions can check exact ids.
   */
  readonly idFactory?: () => ReplayStorageId;
  /**
   * Wall-clock factory invoked at `save()` time to stamp
   * `metadata.savedAt`. Defaults to `() => new Date()`.
   */
  readonly nowFactory?: () => Date;
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/**
 * Generic storage error. Distinct subclass so callers can:
 *
 *   try { await storage.save(replay); }
 *   catch (e) {
 *     if (e instanceof ReplayStorageQuotaExceededError) showFreeUpToast();
 *     else if (e instanceof ReplayStorageError)         showGenericError(e.message);
 *     else                                              throw e;
 *   }
 */
export class ReplayStorageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ReplayStorageError';
  }
}

/**
 * Thrown when a backend refuses a write because the browser quota was
 * hit. Distinct subclass so the replay menu can show a "free up space"
 * toast specifically for this condition. Wraps the original DOMException
 * for diagnostics.
 */
export class ReplayStorageQuotaExceededError extends ReplayStorageError {
  /** The native browser exception that triggered the wrap, if any. */
  public readonly cause?: unknown;
  constructor(message: string, cause?: unknown) {
    super(message);
    this.name = 'ReplayStorageQuotaExceededError';
    if (cause !== undefined) this.cause = cause;
  }
}

/**
 * Thrown when the caller asked for a row that doesn't exist on a path
 * that requires one (e.g. `delete(id)` returns `false` for a missing
 * row, but `save({ id, overwrite: true })` is conceptually an upsert
 * and never throws this).
 */
export class ReplayNotFoundError extends ReplayStorageError {
  constructor(id: ReplayStorageId) {
    super(`Replay not found: ${id}`);
    this.name = 'ReplayNotFoundError';
  }
}

/**
 * Thrown by every storage backend's `load()` (and the related
 * `loadOrThrow`) when the integrity check on a stored row fails — AC
 * 30104 Sub-AC 4.
 *
 * Wraps the underlying {@link ReplayIntegrityError} so the storage
 * layer's public surface still throws a single
 * {@link ReplayStorageError} family. The wrapped error is exposed via
 * `cause` (the underlying integrity error carries the
 * `expected` / `actual` / `algorithm` / `kind` diagnostic fields the
 * replay menu surfaces in its "Replay corrupted" toast).
 *
 * The replay menu can branch on this exact subclass to:
 *
 *   • Show a corruption-specific message (rather than the generic
 *     "couldn't load — JSON parse error").
 *   • Offer a "Delete corrupted replay" action that purges the row
 *     without trying to play it back.
 *   • Log a diagnostic event so we can spot patterns of corruption
 *     across users.
 */
export class ReplayCorruptedError extends ReplayStorageError {
  /** The underlying integrity error that triggered the wrap. */
  readonly cause: ReplayIntegrityError;
  /** Storage row id that failed the integrity check. */
  readonly id: ReplayStorageId;
  constructor(id: ReplayStorageId, cause: ReplayIntegrityError) {
    super(
      `Replay '${id}' failed integrity check (${cause.kind}): ${cause.message}`,
    );
    this.name = 'ReplayCorruptedError';
    this.cause = cause;
    this.id = id;
  }
}

// ---------------------------------------------------------------------------
// Interface
// ---------------------------------------------------------------------------

/**
 * Backend-agnostic CRUD interface. Every backend implements every
 * method; callers code against this type so the replay menu can swap
 * IDB for localStorage at runtime without changes.
 *
 * Async on every method even when the backend can answer synchronously —
 * see the module header for the rationale.
 */
export interface ReplayStorage {
  /** Discriminator so HUDs / logs can show which backend is in use. */
  readonly backend: ReplayStorageBackend;

  /**
   * Persist a replay. Returns the storage-side metadata (including the
   * new row's id, `savedAt`, `sizeBytes`).
   *
   * Validation:
   *   • The replay must round-trip through {@link deserializeReplay} —
   *     a deformed `ReplayFile` is rejected before it touches storage.
   *   • If `options.id` is supplied, it must be a non-empty string.
   *   • If a row with that id already exists and `overwrite !== true`,
   *     throws {@link ReplayStorageError}.
   *
   * On quota-exceeded the partially-written row is cleaned up and the
   * backend rethrows {@link ReplayStorageQuotaExceededError}.
   */
  save(replay: ReplayFile, options?: SaveReplayOptions): Promise<StoredReplayMetadata>;

  /**
   * Load a replay by id. Returns `null` (not throws) when the row is
   * absent — callers that prefer the throwing form can use
   * {@link ReplayStorage.loadOrThrow}.
   *
   * The returned `replay` field is a frozen, validated {@link ReplayFile}.
   * If the stored bytes fail validation (an older app version wrote a
   * blob today's deserialiser refuses), throws
   * {@link ReplayStorageError}; the offending row stays in storage so
   * the user can decide to delete it manually.
   */
  load(id: ReplayStorageId): Promise<StoredReplay | null>;

  /** Sugar — `load()` that throws {@link ReplayNotFoundError} on miss. */
  loadOrThrow(id: ReplayStorageId): Promise<StoredReplay>;

  /**
   * List every replay's metadata, newest `savedAt` first. Cheap — does
   * not load any replay's input timeline.
   */
  list(): Promise<ReadonlyArray<StoredReplayMetadata>>;

  /** Membership check. */
  has(id: ReplayStorageId): Promise<boolean>;

  /**
   * Delete a row. Returns `true` when a row was removed, `false` when
   * the row was absent. Idempotent — never throws on a missing row.
   */
  delete(id: ReplayStorageId): Promise<boolean>;

  /** Drop every replay. */
  clear(): Promise<void>;

  /** Aggregate stats for the storage HUD. */
  getStats(): Promise<ReplayStorageStats>;

  /**
   * Release backend resources (close the IDB connection, drop the
   * localStorage prefix cache). Idempotent. After `close()` further
   * method calls throw {@link ReplayStorageError}.
   */
  close(): Promise<void>;
}

// ---------------------------------------------------------------------------
// Helpers shared between backends
// ---------------------------------------------------------------------------

/**
 * UTF-8 byte length of a string. `TextEncoder` is available in every
 * modern browser and Node 18+. Falls back to `s.length` (under-counts
 * multibyte) if absent — better than crashing on a save.
 */
export function utf8ByteLength(s: string): number {
  if (typeof TextEncoder !== 'undefined') {
    return new TextEncoder().encode(s).length;
  }
  return s.length;
}

/**
 * Serialise a replay to a stable JSON string for both IDB and
 * localStorage. Compact (no pretty-print) — this is machine-read
 * persistence, not a save-to-disk export.
 *
 * Re-uses {@link serializeReplayToString} so the same writer powers
 * `downloadReplay`, IDB persistence, and localStorage persistence —
 * three storage paths, one canonical wire format.
 */
export function serializeReplayForStorage(replay: ReplayFile): string {
  // The replay is already a frozen ReplayFile; unwrap the SerializeReplayOptions
  // shape the writer expects.
  const opts: SerializeReplayOptions = {
    matchConfig: replay.matchConfig,
    capturedFrames: replay.inputTimeline.entries.map((e) => ({
      frame: e.frame,
      inputs: e.inputs,
    })),
    recordedAt: new Date(replay.metadata.recordedAt),
    engineVersion: replay.metadata.engineVersion,
    notes: replay.metadata.notes,
    fixedTimestepMs: replay.metadata.fixedTimestepMs,
  };
  return serializeReplayToString(opts, false);
}

/**
 * Build {@link StoredReplayMetadata} from a replay + storage-side
 * fields. Centralised so both backends produce the same shape for the
 * same input.
 *
 * `checksum` is required so the metadata always carries a valid
 * integrity tag — passing `undefined` would let an upstream backend
 * forget to compute one and silently weaken the integrity guarantee.
 * The IDB / localStorage / memory backends compute the checksum from
 * the canonical serialised payload they're about to write and pass it
 * here.
 */
export function buildStoredReplayMetadata(
  id: ReplayStorageId,
  savedAt: string,
  sizeBytes: number,
  replay: ReplayFile,
  checksum: string,
  checksumAlgorithm: ReplayChecksumAlgorithm = CHECKSUM_ALGORITHM,
): StoredReplayMetadata {
  return Object.freeze({
    id,
    savedAt,
    sizeBytes,
    recordedAt: replay.metadata.recordedAt,
    durationFrames: replay.metadata.durationFrames,
    notes: replay.metadata.notes,
    stageId: replay.matchConfig.stageId,
    playerCount: replay.metadata.playerCount,
    rngSeed: replay.rngSeed,
    engineVersion: replay.metadata.engineVersion,
    checksum,
    checksumAlgorithm,
  });
}

/**
 * Compute the integrity checksum for a serialised replay payload —
 * AC 30104 Sub-AC 4. Convenience wrapper that lets every backend share
 * one entry-point so a future algorithm bump only has to change one
 * call site.
 */
export function computeReplayPayloadChecksum(serialized: string): string {
  return computeReplayChecksum(serialized);
}

/**
 * Verify a serialised replay payload against its stored checksum,
 * surfacing any mismatch as {@link ReplayCorruptedError} keyed by row
 * id — AC 30104 Sub-AC 4. Used by every backend's `load()` path so the
 * replay menu only has to catch one error type.
 */
export function assertReplayPayloadIntegrity(
  id: ReplayStorageId,
  serialized: string,
  expectedChecksum: string,
  algorithm: string = CHECKSUM_ALGORITHM,
): void {
  try {
    verifyReplayChecksum(serialized, expectedChecksum, algorithm);
  } catch (err) {
    if (err instanceof ReplayIntegrityError) {
      throw new ReplayCorruptedError(id, err);
    }
    throw err;
  }
}

/**
 * Validate a replay before write — round-trip it through the
 * deserialiser. Cheap (writes are rare relative to gameplay frames) and
 * catches the case where some upstream code produced a malformed
 * `ReplayFile`-ish object that would never load back.
 */
export function validateReplayForWrite(replay: ReplayFile): ReplayFile {
  if (replay === null || replay === undefined || typeof replay !== 'object') {
    throw new ReplayStorageError(
      'ReplayStorage.save: replay must be a ReplayFile object',
    );
  }
  // Quick magic / version sniff before the heavier round-trip.
  if ((replay as ReplayFile).format !== REPLAY_FORMAT_MAGIC) {
    throw new ReplayStorageError(
      `ReplayStorage.save: replay.format must equal '${REPLAY_FORMAT_MAGIC}'`,
    );
  }
  if ((replay as ReplayFile).version !== REPLAY_FORMAT_VERSION) {
    throw new ReplayStorageError(
      `ReplayStorage.save: replay.version must equal ${REPLAY_FORMAT_VERSION}`,
    );
  }
  // Round-trip via serialise → deserialise to confirm the bytes are valid.
  // We cannot just call `deserializeReplay(replay)` directly because the
  // input is already a ReplayFile (would round-trip-clone it for free,
  // but we want to fail fast on a malformed timeline).
  let parsed: ReplayFile;
  try {
    parsed = deserializeReplay(JSON.parse(serializeReplayForStorage(replay)));
  } catch (err) {
    if (err instanceof ReplayFileError) {
      throw new ReplayStorageError(
        `ReplayStorage.save: replay validation failed — ${err.message}`,
      );
    }
    throw err;
  }
  return parsed;
}

/** Default id factory — `crypto.randomUUID` when available, else fallback. */
export function defaultIdFactory(): () => ReplayStorageId {
  // Bind once. The crypto reference is checked lazily so a Node test
  // env without `crypto.randomUUID` (very old Node) still works.
  let counter = 0;
  return () => {
    const cryptoRef = (globalThis as { crypto?: Crypto }).crypto;
    if (cryptoRef !== undefined && typeof cryptoRef.randomUUID === 'function') {
      try {
        return cryptoRef.randomUUID();
      } catch {
        // Some sandboxes throw on `randomUUID` (insecure context, etc.) —
        // fall through to the counter fallback.
      }
    }
    counter += 1;
    return `replay-${Date.now().toString(36)}-${counter.toString(36)}`;
  };
}

/**
 * Detect whether a thrown value is a quota-exceeded `DOMException`. The
 * exact name varies between browsers (older Firefox uses
 * `NS_ERROR_DOM_QUOTA_REACHED`, Safari has historically thrown a plain
 * `Error`). This helper is conservative — it returns true on any
 * recognisable form.
 */
export function isQuotaExceededError(err: unknown): boolean {
  if (err === null || err === undefined) return false;
  if (typeof err !== 'object') return false;
  const e = err as { name?: unknown; code?: unknown; message?: unknown };
  if (typeof e.name === 'string') {
    if (
      e.name === 'QuotaExceededError' ||
      e.name === 'NS_ERROR_DOM_QUOTA_REACHED'
    ) {
      return true;
    }
  }
  if (typeof e.code === 'number' && (e.code === 22 || e.code === 1014)) {
    // Legacy DOMException codes for QUOTA_EXCEEDED_ERR (22) and
    // Firefox's old NS_ERROR_DOM_QUOTA_REACHED (1014).
    return true;
  }
  if (typeof e.message === 'string' && /quota/i.test(e.message)) {
    return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Memory backend
// ---------------------------------------------------------------------------

/**
 * In-process, non-persistent storage. Useful for:
 *
 *   • The vitest suite — no IDB shim needed.
 *   • Headless CLI tooling (e.g. an "export every replay to JSON" script).
 *   • A first-run demo mode where we don't want to clutter the user's
 *     `localStorage` until they save their first match.
 *
 * Implements the same interface as the persistent backends so feature
 * tests can swap in this backend with a single line.
 */
export class MemoryReplayStorage implements ReplayStorage {
  public readonly backend = 'memory' as const;
  private readonly idFactory: () => ReplayStorageId;
  private readonly nowFactory: () => Date;
  private readonly rows: Map<ReplayStorageId, { metadata: StoredReplayMetadata; serialized: string }> = new Map();
  private closed = false;

  constructor(options: ReplayStorageOptions = {}) {
    this.idFactory = options.idFactory ?? defaultIdFactory();
    this.nowFactory = options.nowFactory ?? (() => new Date());
  }

  async save(
    replay: ReplayFile,
    options: SaveReplayOptions = {},
  ): Promise<StoredReplayMetadata> {
    this.assertOpen();
    const validated = validateReplayForWrite(replay);
    const id = options.id ?? this.idFactory();
    if (typeof id !== 'string' || id.length === 0) {
      throw new ReplayStorageError('ReplayStorage.save: id must be a non-empty string');
    }
    if (this.rows.has(id) && options.overwrite !== true) {
      throw new ReplayStorageError(
        `ReplayStorage.save: row '${id}' already exists; pass overwrite: true to replace`,
      );
    }
    const serialized = serializeReplayForStorage(validated);
    const sizeBytes = utf8ByteLength(serialized);
    const checksum = computeReplayPayloadChecksum(serialized);
    const savedAt = (options.savedAt ?? this.nowFactory()).toISOString();
    const metadata = buildStoredReplayMetadata(
      id,
      savedAt,
      sizeBytes,
      validated,
      checksum,
    );
    this.rows.set(id, { metadata, serialized });
    return metadata;
  }

  async load(id: ReplayStorageId): Promise<StoredReplay | null> {
    this.assertOpen();
    const row = this.rows.get(id);
    if (row === undefined) return null;
    // AC 30104 Sub-AC 4 — verify the integrity checksum *before* the
    // JSON parse so a known-corrupted payload surfaces as a
    // ReplayCorruptedError rather than the parser's lower-level
    // "JSON is malformed" message. The verifier throws
    // ReplayCorruptedError on mismatch, which the storage interface
    // commits to surfacing untouched.
    assertReplayPayloadIntegrity(
      id,
      row.serialized,
      row.metadata.checksum,
      row.metadata.checksumAlgorithm,
    );
    let replay: ReplayFile;
    try {
      replay = deserializeReplay(JSON.parse(row.serialized));
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new ReplayStorageError(`ReplayStorage.load: row '${id}' is corrupt — ${msg}`);
    }
    return Object.freeze({ metadata: row.metadata, replay });
  }

  async loadOrThrow(id: ReplayStorageId): Promise<StoredReplay> {
    const r = await this.load(id);
    if (r === null) throw new ReplayNotFoundError(id);
    return r;
  }

  async list(): Promise<ReadonlyArray<StoredReplayMetadata>> {
    this.assertOpen();
    const all = [...this.rows.values()].map((r) => r.metadata);
    // Newest savedAt first; tie-break on id (lexicographic) for stable order.
    all.sort((a, b) => {
      if (a.savedAt !== b.savedAt) return a.savedAt < b.savedAt ? 1 : -1;
      return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
    });
    return Object.freeze(all);
  }

  async has(id: ReplayStorageId): Promise<boolean> {
    this.assertOpen();
    return this.rows.has(id);
  }

  async delete(id: ReplayStorageId): Promise<boolean> {
    this.assertOpen();
    return this.rows.delete(id);
  }

  async clear(): Promise<void> {
    this.assertOpen();
    this.rows.clear();
  }

  async getStats(): Promise<ReplayStorageStats> {
    this.assertOpen();
    let total = 0;
    for (const row of this.rows.values()) total += row.metadata.sizeBytes;
    return Object.freeze({
      count: this.rows.size,
      totalBytes: total,
      quotaBytes: null,
      usageBytes: total,
      backend: this.backend,
    });
  }

  async close(): Promise<void> {
    this.closed = true;
    this.rows.clear();
  }

  private assertOpen(): void {
    if (this.closed) {
      throw new ReplayStorageError('ReplayStorage: backend is closed');
    }
  }
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * Options for {@link openReplayStorage}. Same shape as
 * {@link ReplayStorageOptions} plus a `prefer` knob the test suite uses
 * to force a specific backend.
 */
export interface OpenReplayStorageOptions extends ReplayStorageOptions {
  /**
   * Pin a specific backend. Default `'auto'` probes IDB → localStorage
   * → memory in order. Tests use the explicit values.
   */
  readonly prefer?: 'auto' | ReplayStorageBackend;
  /**
   * Optional database / prefix name. Defaults to `'platform-fighter-replays'`
   * (IDB database name) or `'pf:replay:'` (localStorage key prefix).
   * Exposed so tests can isolate runs.
   */
  readonly namespace?: string;
  /**
   * Optional injected IDBFactory. Defaults to `globalThis.indexedDB`.
   * Tests pass an in-memory shim.
   */
  readonly indexedDBFactory?: IDBFactory;
  /**
   * Optional injected Storage (localStorage). Defaults to
   * `globalThis.localStorage`. Tests pass an in-memory shim.
   */
  readonly localStorageRef?: Storage;
  /**
   * Optional `navigator.storage.estimate` override for tests. Returns
   * `null`/missing fields when unsupported. Production reads
   * `navigator.storage` directly.
   */
  readonly estimateStorage?: () => Promise<{ usage?: number; quota?: number }>;
}

/**
 * Probe the runtime and return the best available backend. Order:
 *
 *   1. IndexedDB if `globalThis.indexedDB` is callable AND
 *      `prefer !== 'localstorage' | 'memory'`.
 *   2. localStorage if `globalThis.localStorage` exposes get/set/remove
 *      AND IDB rejected (or `prefer === 'localstorage'`).
 *   3. {@link MemoryReplayStorage} as a last resort.
 *
 * The factory is the only async entry — IDB requires an open call. The
 * fallback backends are constructable synchronously, but the function
 * resolves uniformly so callers always `await`.
 */
export async function openReplayStorage(
  options: OpenReplayStorageOptions = {},
): Promise<ReplayStorage> {
  const prefer = options.prefer ?? 'auto';

  // Memory short-circuit — useful for tests + the headless CLI.
  if (prefer === 'memory') {
    return new MemoryReplayStorage(options);
  }

  if (prefer === 'auto' || prefer === 'indexeddb') {
    const idbFactory =
      options.indexedDBFactory ?? (globalThis as { indexedDB?: IDBFactory }).indexedDB;
    if (idbFactory !== undefined && typeof idbFactory.open === 'function') {
      try {
        // Lazy-import the IDB backend so headless callers don't pay the
        // module's parse cost when they only want memory storage.
        const mod = await import('./IndexedDBReplayStorage');
        return await mod.IndexedDBReplayStorage.open({
          ...options,
          indexedDBFactory: idbFactory,
        });
      } catch (err) {
        if (prefer === 'indexeddb') {
          // Caller explicitly wanted IDB — surface the failure rather
          // than silently falling back.
          throw new ReplayStorageError(
            `openReplayStorage: IndexedDB backend unavailable — ${
              err instanceof Error ? err.message : String(err)
            }`,
          );
        }
        // Auto mode — fall through to localStorage probe.
      }
    } else if (prefer === 'indexeddb') {
      throw new ReplayStorageError(
        'openReplayStorage: prefer=indexeddb but globalThis.indexedDB is unavailable',
      );
    }
  }

  if (prefer === 'auto' || prefer === 'localstorage') {
    const lsRef =
      options.localStorageRef ?? (globalThis as { localStorage?: Storage }).localStorage;
    if (lsRef !== undefined && typeof lsRef.setItem === 'function') {
      const mod = await import('./LocalStorageReplayStorage');
      return new mod.LocalStorageReplayStorage({
        ...options,
        localStorageRef: lsRef,
      });
    } else if (prefer === 'localstorage') {
      throw new ReplayStorageError(
        'openReplayStorage: prefer=localstorage but globalThis.localStorage is unavailable',
      );
    }
  }

  // Last resort.
  return new MemoryReplayStorage(options);
}

/**
 * Re-export {@link serializeReplay} as the canonical "build a ReplayFile
 * from a recorded match" entrypoint, kept here so callers using the
 * storage layer don't need to import from two replay modules.
 */
export { serializeReplay };
